version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: "weekly"
  assignees:
  - yeldiRium
  labels:
  - Dependencies
  allow:
  - dependency-type: direct
  commit-message:
    prefix: chore
    prefix-development: chore

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  assignees:
  - yeldiRium
  labels:
  - Dependencies
  commit-message:
    prefix: chore
