name: QA

on: pull_request

permissions:
  contents: read
  packages: read

jobs:
  qa:
    name: QA
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Use Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Run QA
      run: |
        make qa
    - name: Build artifacts
      run: |
        make build
